services:
    odiseo_sylius_report_plugin.controller.action.city_search:
        class: Odiseo\SyliusReportPlugin\Controller\Action\CitySearchAction
        public: true
        arguments:
            - "@sylius.repository.address"
            - "@sylius.repository.country"
            - "@fos_rest.view_handler.default"

    odiseo_sylius_report_plugin.controller.action.province_search:
        class: Odiseo\SyliusReportPlugin\Controller\Action\ProvinceSearchAction
        public: true
        arguments:
            - "@sylius.repository.address"
            - "@sylius.repository.province"
            - "@sylius.repository.country"
            - "@fos_rest.view_handler.default"

    odiseo_sylius_report_plugin.controller.action.postcode_search:
        class: Odiseo\SyliusReportPlugin\Controller\Action\PostcodeSearchAction
        public: true
        arguments:
            - "@sylius.repository.address"
            - "@sylius.repository.country"
            - "@fos_rest.view_handler.default"

    odiseo_sylius_report_plugin.controller.action.product_search:
        class: Odiseo\SyliusReportPlugin\Controller\Action\ProductSearchAction
        public: true
        arguments:
            - "@sylius.repository.product"
            - "@sylius.context.locale"
            - "@fos_rest.view_handler.default"
