services:
    odiseo_sylius_report.repository.order:
        class: Odiseo\SyliusReportPlugin\Repository\OrderRepository
        parent: sylius.repository.order

    odiseo_sylius_report.repository.address:
        class: Odiseo\SyliusReportPlugin\Repository\AddressRepository
        parent: sylius.repository.address