imports:
    - { resource: services/controller.yml }
    - { resource: services/form.yml }
    - { resource: services/repository.yml }
    - { resource: services/renderer.yml }
    - { resource: services/data_fetcher.yml }

services:
    odiseo_sylius_report.filter.query_filter:
        class: Odiseo\SyliusReportPlugin\Filter\QueryFilter
        arguments: ["@doctrine.orm.entity_manager"]

    #REGISTRY
    odiseo_sylius_report.registry.data_fetcher:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments: ['Odiseo\SyliusReportPlugin\DataFetcher\DataFetcherInterface', 'data fetcher']

    odiseo_sylius_report.registry.renderer:
        class: Sylius\Component\Registry\ServiceRegistry
        arguments: ['Odiseo\SyliusReportPlugin\Renderer\RendererInterface', 'renderer']

    odiseo_sylius_report.data_fetcher:
        class: Odiseo\SyliusReportPlugin\DataFetcher\DelegatingDataFetcher
        public: true
        arguments: ['@odiseo_sylius_report.registry.data_fetcher']

    odiseo_sylius_report.renderer:
        class: Odiseo\SyliusReportPlugin\Renderer\DelegatingRenderer
        public: true
        arguments: ['@odiseo_sylius_report.registry.renderer']

    #LISTENERS
    odiseo_sylius_report.listener.admin.menu_builder:
        class: Odiseo\SyliusReportPlugin\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }