Odiseo\SyliusReportPlugin\Model\Report:
    type: mappedSuperclass
    table: odiseo_report
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
        description:
            type: string
            nullable: true
        code:
            type: string
            unique: true
        renderer:
            type: string
        rendererConfiguration:
            type: array
            column: renderer_configuration
        dataFetcher:
            type: string
            column: data_fetcher
        dataFetcherConfiguration:
            type: array
            column: data_fetcher_configuration
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update
