Odiseo\SyliusReportPlugin\Model\Report:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [code]
            message: 'odiseo_sylius_report.report.code.unique'
            groups: ['odiseo']
    properties:
        code:
            - NotBlank:
                message: 'odiseo_sylius_report.report.code.not_blank'
                groups: ['odiseo']
            - Length:
                min: 2
                max: 250
                minMessage: 'odiseo_sylius_report.report.code.min_length'
                maxMessage: 'odiseo_sylius_report.report.code.max_length'
                groups: ['odiseo']
        name:
            - NotBlank:
                message: 'odiseo_sylius_report.report.name.not_blank'
                groups: ['odiseo']
            - Length:
                min: 2
                max: 250
                minMessage: 'odiseo_sylius_report.report.name.min_length'
                maxMessage: 'odiseo_sylius_report.report.name.max_length'
                groups: ['odiseo']
