sylius_grid:
    grids:
        odiseo_sylius_report_plugin_admin_report:
            driver:
                name: doctrine/orm
                options:
                    class: "%odiseo_sylius_report_plugin.model.report.class%"
            sorting:
                id: asc
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                    sortable: ~
                name:
                    type: twig
                    label: sylius.ui.name
                    path: .
                    options:
                        template: "@SyliusUi/Grid/Field/nameAndDescription.html.twig"
                renderer:
                    type: twig
                    label: odiseo_sylius_report_plugin.form.renderer.label
                    options:
                        template: "@OdiseoSyliusReportPlugin/Grid/Field/dataTrans.html.twig"
                dataFetcher:
                    type: twig
                    label: odiseo_sylius_report_plugin.form.data_fetcher
                    options:
                        template: "@OdiseoSyliusReportPlugin/Grid/Field/dataTrans.html.twig"
                createdAt:
                    type: datetime
                    label: sylius.ui.creation_date
                    sortable: ~
            filters:
                name:
                    type: string
                    label: sylius.ui.name
            actions:
                main:
                    create:
                        type: create
                item:
                    show:
                        type: show
                    update:
                        type: update
                    delete:
                        type: delete
                    export:
                        type: export
                        label: odiseo_sylius_report_plugin.ui.export
                        options:
                            link:
                                route: odiseo_sylius_report_plugin_admin_report_export
                                parameters:
                                    id: resource.id

    templates:
        action:
            export: "@OdiseoSyliusReportPlugin/Grid/Action/export.html.twig"
