odiseo_sylius_report_admin_report:
    resource: |
        alias: odiseo_sylius_report.report
        section: admin
        templates: OdiseoSyliusReportPlugin:Crud
        except: ['show']
        redirect: show
        grid: odiseo_sylius_report_admin_report
        permission: true
        vars:
            all:
                subheader: odiseo_sylius_report.ui.manage_reports
                templates:
                    form: '@OdiseoSyliusReportPlugin/_form.html.twig'
            index:
                icon: bar chart
    type: sylius.resource

odiseo_sylius_report_admin_report_show:
    path: /reports/{id}
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_report.controller.report:renderAction
        _sylius:
            template: '@OdiseoSyliusReportPlugin/show.html.twig'
    requirements:
        id: '\d+'

odiseo_sylius_report_admin_report_export:
    path: /reports/{id}/export.{_format}
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_report.controller.report:exportAction
        _format: csv
    requirements:
        id: '\d+'
